config/routes.rb
Rails.application.routes.draw do
  root to: 'beeps#index'

  resources :beeps
  devise_for :users
  resources :users, only: [:show] do
    resources :connections, only: [:create, :destroy]
  end
end

app/models/beep.rb
class Beep < ActiveRecord::Base
  validates :beep, presence: true
  belongs_to :user
  has_many :tags
  has_many :users, through: :tags

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  default_scope { order('created_at DESC') }

  after_create :name_checker

private
  def name_checker
    names = []
    User.all.each do |user|
      if self.beep.match("~" + user.name)
        names << self.beep.match("~" + user.name).to_s.slice(1..-1)
      end
    end
    names.each do |name|
      self.tags.create(user_id: User.find_by(name: name).id)
    end
  end

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :beeper, :class_name => 'User'
  belongs_to :follower, :class_name => 'User'

  validates_uniqueness_of :beeper_id, scope: :follower_id

  after_create :send_follower_notification

  def send_follower_notification
    UserMailer.follower_notification(self.follower, self.beeper).deliver
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :beep
  validates_uniqueness_of :user_id, scope: :beep_id

  after_create :send_tag_notification

  def send_tag_notification
    UserMailer.tag_notification(self.user, self.beep).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true

  after_create :send_welcome_message #, other callbacks..

  has_many :beeps, dependent: :destroy

  has_many :connections, foreign_key: 'follower_id', dependent: :destroy
  has_many :beepers, through: :connections, source: :beeper
  has_many :reverse_connections, foreign_key: 'beeper_id', class_name: 'Connection', dependent: :destroy
  has_many :followers, through: :reverse_connections, source: :follower

  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end

  def feed
    beepers_beeps = []
    self.beepers.each do |beeper|
      beepers_beeps << beeper.beeps
    end
    beepers_beeps.flatten
  end

  def following? user
    Connection.find_by({beeper_id: user.id, follower_id: self.id})
  end

  def follow user
    Connection.create({beeper_id: user.id, follower_id: self.id})
  end

  def unfollow user
    Connection.find_by({beeper_id: user.id, follower_id: self.id}).destroy
  end

end

app/controllers/Users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_in) << :email
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beeps_controller.rb
class BeepsController < ApplicationController

  def index
  @beeps = Beep.all.page(params[:page]).per(7)
  @beep = Beep.new
  end

  def new
    @beep = current_user.beeps.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @beep = current_user.beeps.new(beep_params)
    @beep.photo = params[:beep][:photo]
    if @beep.save
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end
    else
      render 'new'
    end
  end

private
  def beep_params
    params.require(:beep).permit(:beep, :photo)
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    @connection = Connection.find_by(beeper_id: @user.id, follower_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @connection = Connection.find_by(beeper_id: @user.id, follower_id: current_user.id)

    current_user.unfollow(@user)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    unless Connection.find_by(beeper_id: @user.id, follower_id: current_user.id)
      @connection = Connection.new
    else
      @connection = Connection.find_by(beeper_id: @user.id, follower_id: current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beeps/_beep.html.erb
<div class="panel panel-body">
<div class="row">
    <div class="col-md-4"><%= link_to beep.user.name, user_path(beep.user) %> beeped <%= beep.beep %></div>
    <% unless beep.photo.url == '/images/original/missing.png' %>
      <div class="col-md-4"><%= image_tag beep.photo.url(:thumb) %></div>
    <% end %>
</div>
</div>

app/views/beeps/_form.html.erb
<%= form_for @beep, :html => { :multipart => true }, remote: true do |f| %>
    <%= f.label :beep %>
    <%= f.text_field :beep %>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  <%= f.submit(class: "btn btn-info") %>
<% end %>

app/views/beeps/create.js.erb
$('#new_beep').remove();
$('#beeper').show();
$('#user_beeps').prepend('<%= j render(@beep) %>');

app/views/beeps/index.html.erb
<%= link_to "New Beep", new_beep_path, id: "beeper", class: "btn btn-default", remote: true %>
<div class="panel panel-default" id="user_beeps"><%= render @beeps %></div>

<%= paginate @beeps %>

app/views/beeps/new.js.erb
$('#beeper').hide().after('<%= j render("form") %>');

app/views/connections/_follow.html.erb
<%= link_to "Follow", user_connections_path(@user), id: "follow_beeper", class: "btn btn-warning", method: :post, remote: true %>

app/views/connections/_unfollow.html.erb
<%= link_to "Unfollow", "/users/#{@user.id}/connections/#{@connection.id}", id: "unfollow_beeper", class: "btn btn-success", method: :delete, remote: true %>

app/views/connections/create.js.erb
$('#follow_beeper').hide();
$('#unfollow_beeper').show();
$("#flashy").text("You are following <%= @user.name %>");
$("#flashy").fadeOut(2000);

app/views/connections/destroy.js.erb
$('#unfollow_beeper').hide();
$('#follow_beeper').show();
$("#flashy").text("You are no longer following <%= @user.name %>");
$("#flashy").fadeOut(2000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= flash[:alert] %>

<div class="container">
  <div id="user_nav">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<div id="flashy"></div>
<h2><%= @user.name %>
  <%= render 'connections/follow' %>
  <%= render 'connections/unfollow' %>
  <% if current_user.following?(@user) %>
    <script>
      $('#unfollow_beeper').show();
    </script>
  <% else %>
    <script>
      $('#follow_beeper').show();
    </script>
  <% end %>
</h2>
<div class="row">
  <div class="col-md-6">
    <h3>Your Beeps!</h3>
    <div class="panel panel-default">
      <%= render @user.beeps %>
    </div>
  </div>
<% if current_user == @user %>
  <div class="col-md-6">
    <h3>Beepers you're following</h3>
    <div class="panel panel-default">
      <%= render current_user.feed %>
    </div>
  </div>
<% end %>
</div>